[package]
name = "site-util"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "siu"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
env_logger = "0.9"
